<?php get_header(); ?>
<?php
$centers = array(
    array( 'name' => 'Jayanagar Center', 'area' => 'Jayanagar 4th Block, Bengaluru', 'image' => 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=760&q=80', 'phone' => '080 2664 4444', 'hours' => 'Morning & Evening', 'programs' => 'Yoga for Beginners, Yoga Therapy, Pranayama', 'address' => 'No. 12, 4th Block, Jayanagar, Bengaluru – 560011', 'email' => 'jayanagar@rashtrotthana.org' ),
    array( 'name' => 'Basavanagudi Center', 'area' => 'Basavanagudi, Bengaluru', 'image' => 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=760&q=80', 'phone' => '080 2665 1234', 'hours' => 'Morning & Evening', 'programs' => 'Yoga for All, Yoga Therapy, Children’s Programs', 'address' => 'No. 34, Bull Temple Road, Basavanagudi, Bengaluru – 560004', 'email' => 'basavanagudi@rashtrotthana.org' ),
    array( 'name' => 'Malleswaram Center', 'area' => '18th Cross, Malleswaram', 'image' => 'https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=760&q=80', 'phone' => '080 2336 7890', 'hours' => 'Morning & Evening', 'programs' => 'Yoga for All, Pranayama, Meditation', 'address' => 'Rashtrotthana Complex, 18th Cross, Malleswaram, Bengaluru – 560003', 'email' => 'malleswaram@rashtrotthana.org' ),
    array( 'name' => 'Yelahanka Center', 'area' => 'Yelahanka New Town, Bengaluru', 'image' => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=760&q=80', 'phone' => '080 2954 5678', 'hours' => 'Morning & Evening', 'programs' => 'Yoga for Beginners, Fitness Yoga, Therapy', 'address' => 'New Town Main Road, Yelahanka, Bengaluru – 560064', 'email' => 'yelahanka@rashtrotthana.org' ),
);
?>
<main class="rs-centers-page">
 <section class="rs-centers-hero"><div class="rs-centers-hero-image"></div><div class="rs-container rs-centers-hero-inner"><div class="rs-centers-copy"><p class="rs-centers-breadcrumb">Home <span>›</span> Centers</p><h1>Our <em>Centers</em></h1><h2>23+ Centers Across Bengaluru</h2><p>Find a center near you and begin your journey towards health, happiness and inner peace.</p><label class="rs-center-search"><span>⌕</span><input type="search" placeholder="Search by area or center name..." aria-label="Search centers"><button type="button" aria-label="Search centers">⌕</button></label></div></div></section>
 <section class="rs-center-numbers"><div class="rs-container"><div><?php foreach(array(array('23+','Centers'),array('35+','Activities'),array('100+','Instructors'),array('1.5+ Lakh','Lives Touched'),array('3,000+','Daily Practitioners')) as $stat): ?><p><strong><?php echo esc_html($stat[0]); ?></strong><span><?php echo esc_html($stat[1]); ?></span></p><?php endforeach; ?></div></div></section>
 <section class="rs-center-directory"><div class="rs-container"><h2>Find a Center Near You</h2><div class="rs-center-filters"><select aria-label="Select area"><option>All Areas</option><option>Jayanagar</option><option>Malleswaram</option></select><select aria-label="Select activity"><option>All Activities</option><option>Yoga & Wellness</option><option>Fitness & Sports</option></select><select aria-label="Select timing"><option>All Timings</option><option>Morning</option><option>Evening</option></select><button class="rs-clear-filters" type="button">⟲ &nbsp; Clear Filters</button><button class="is-current" type="button">▤ List View</button><button type="button">⌖ Map View</button></div><div class="rs-center-results"><div class="rs-center-list"><p class="rs-results-count">Showing <span>23</span> Centers</p><?php foreach($centers as $index => $center): ?><article class="rs-directory-card" data-center="<?php echo esc_attr(strtolower($center['name'].' '.$center['area'])); ?>"><img src="<?php echo esc_url($center['image']); ?>" alt="" loading="lazy"><div><h3><?php echo esc_html($center['name']); ?></h3><p class="rs-directory-area">⌖ <?php echo esc_html($center['area']); ?></p><p class="rs-directory-hours">☀ <?php echo esc_html($center['hours']); ?></p><p class="rs-directory-programs"><?php echo esc_html($center['programs']); ?></p><p class="rs-directory-phone">☎ <?php echo esc_html($center['phone']); ?></p></div><button class="rs-center-details" type="button" data-modal="center-modal-<?php echo esc_attr($index); ?>">View Details →</button></article><?php endforeach; ?><button class="rs-load-centers" type="button">Load More Centers &nbsp;↓</button></div><div class="rs-real-map"><iframe title="Rashtrotthana centers in Bengaluru" src="https://www.google.com/maps?q=Rashtrotthana%20Yoga%20Bengaluru&z=12&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe></div></div></div></section>
 <section class="rs-center-help"><div class="rs-container"><div><span>⌖</span><p><strong>Can’t find what you’re looking for?</strong><small>We’re here to help you find the perfect center for your needs.</small></p><a href="#">Contact Us →</a></div></div></section>
</main>
<?php foreach($centers as $index => $center): ?><div class="rs-center-modal" id="center-modal-<?php echo esc_attr($index); ?>" aria-hidden="true" role="dialog" aria-modal="true" aria-labelledby="center-modal-title-<?php echo esc_attr($index); ?>"><div class="rs-modal-backdrop" data-close-modal></div><article class="rs-modal-card"><button class="rs-modal-close" type="button" aria-label="Close center details" data-close-modal>×</button><img src="<?php echo esc_url($center['image']); ?>" alt=""><div><p class="rs-modal-kicker">RASHTROTTHANA CENTER</p><h2 id="center-modal-title-<?php echo esc_attr($index); ?>"><?php echo esc_html($center['name']); ?></h2><p class="rs-modal-address">⌖ <?php echo esc_html($center['address']); ?></p><div class="rs-modal-detail-grid"><p><b>Hours</b><?php echo esc_html($center['hours']); ?></p><p><b>Phone</b><?php echo esc_html($center['phone']); ?></p><p><b>Email</b><?php echo esc_html($center['email']); ?></p><p><b>Programs</b><?php echo esc_html($center['programs']); ?></p></div><a href="https://www.google.com/maps/search/?api=1&query=<?php echo rawurlencode($center['address']); ?>" target="_blank" rel="noopener">Get Directions ↗</a></div></article></div><?php endforeach; ?>
<script>document.addEventListener('DOMContentLoaded',function(){var body=document.body,buttons=document.querySelectorAll('.rs-center-details'),closers=document.querySelectorAll('[data-close-modal]'),search=document.querySelector('.rs-center-search input'),cards=document.querySelectorAll('.rs-directory-card');function close(){document.querySelectorAll('.rs-center-modal.is-open').forEach(function(m){m.classList.remove('is-open');m.setAttribute('aria-hidden','true')});body.classList.remove('rs-modal-open')}buttons.forEach(function(b){b.addEventListener('click',function(){var modal=document.getElementById(b.dataset.modal);modal.classList.add('is-open');modal.setAttribute('aria-hidden','false');body.classList.add('rs-modal-open');modal.querySelector('.rs-modal-close').focus()})});closers.forEach(function(b){b.addEventListener('click',close)});document.addEventListener('keydown',function(e){if(e.key==='Escape')close()});search.addEventListener('input',function(){var q=this.value.toLowerCase();cards.forEach(function(c){c.hidden=!c.dataset.center.includes(q)})})});</script>
<?php get_footer(); ?>
