<?php get_header(); ?>
<?php
$events = array(
 array('21','JUN','International Yoga Day Celebration 2026','Jayanagar Center','7:00 AM – 9:00 AM','Join us for celebrating the transformative power of Yoga.','Special Event','https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80'),
 array('05','JUL','Summer Yoga Camp for Children','Basavanagudi Center','9:00 AM – 1:00 PM','Fun, learning and yoga-based activities for children aged 7–14.','Children','https://images.unsplash.com/photo-1599443015574-be5fe8a05783?auto=format&fit=crop&w=800&q=80'),
 array('15','JUL','Yoga for Stress Relief Workshop','Malleswaram Center','5:00 PM – 7:00 PM','A workshop to help you manage stress through yoga and meditation.','Workshop','https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=800&q=80'),
 array('30','JUL','Meditation & Pranayama Workshop','Online & Offline','6:00 PM – 8:00 AM','Discover the art of breath and mindfulness for inner peace.','Wellness','https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80')
);
$articles = array(
 array('Rashtrotthana Yoga Inaugurates New Center in HSR Layout','May 20, 2026','News','A new chapter begins as we expand our reach and bring Yoga closer to communities.','https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=800&q=80'),
 array('Yoga Teachers Training Program Completed','May 15, 2026','Achievement','New batch of dedicated instructors complete intensive training successfully.','https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=800&q=80'),
 array('Community Wellness Program Held in Whitefield','May 10, 2026','Community','Promoting health and harmony through Yoga sessions for corporates and residents.','https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80'),
 array('The Connection Between Yoga and Nutrition','May 08, 2026','Health Tips','Explore how mindful eating and yoga together create a balanced and vibrant lifestyle.','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80')
);
?>
<main class="rs-events-page">
<section class="rs-events-hero"><div class="rs-events-hero-image"></div><div class="rs-container rs-events-hero-inner"><div><p class="rs-events-breadcrumb">Home <span>›</span> Events &amp; News</p><h1>Events &amp; <em>News</em></h1><p>Stay updated with our upcoming events, inspiring programs and the latest news from our Yoga community.</p><div><a href="#upcoming" class="rs-event-hero-primary">▣ &nbsp; Explore Events</a><a href="#news" class="rs-event-hero-secondary">Read News &nbsp;◉</a></div></div></div></section>
<section class="rs-events-filter"><div class="rs-container"><div><nav><a class="is-active" href="#upcoming">Upcoming Events</a><a href="#past">Past Events</a><a href="#news">News &amp; Articles</a></nav><select aria-label="Event category"><option>All Categories</option><option>Wellness</option><option>Workshop</option></select><label><input type="date" aria-label="Select date"></label><label class="rs-event-search">⌕ <input type="search" aria-label="Search events" placeholder="Search events or news..."><button type="button">⌕</button></label></div></div></section>
<section class="rs-events-list" id="upcoming"><div class="rs-container"><div class="rs-events-section-heading"><h2>Upcoming Events</h2><a href="#upcoming">View all events &nbsp;→</a></div><div class="rs-events-card-grid"><?php foreach($events as $event): ?><article class="rs-event-list-card"><div class="rs-event-card-image"><img src="<?php echo esc_url($event[7]); ?>" alt="" loading="lazy"><span><b><?php echo esc_html($event[0]); ?></b><?php echo esc_html($event[1]); ?></span></div><div class="rs-event-list-body"><h3><?php echo esc_html($event[2]); ?></h3><p class="rs-event-meta">⌖ <?php echo esc_html($event[3]); ?></p><p class="rs-event-meta">◷ <?php echo esc_html($event[4]); ?></p><p class="rs-event-description"><?php echo esc_html($event[5]); ?></p><div><i><?php echo esc_html($event[6]); ?></i><a class="rs-event-register" href="#register">Register Now →</a></div></div></article><?php endforeach; ?></div></div></section>
<section class="rs-events-news" id="news"><div class="rs-container"><div class="rs-events-section-heading"><h2>News &amp; Articles</h2><a href="#news">View all news &nbsp;→</a></div><div class="rs-news-grid"><?php foreach($articles as $article): ?><article><img src="<?php echo esc_url($article[4]); ?>" alt="" loading="lazy"><div><h3><?php echo esc_html($article[0]); ?></h3><p class="rs-news-meta"><?php echo esc_html($article[1]); ?> &nbsp;•&nbsp; <?php echo esc_html($article[2]); ?></p><p><?php echo esc_html($article[3]); ?></p><a href="#news">Read More →</a></div></article><?php endforeach; ?></div></div></section>
<section class="rs-events-subscribe" id="register"><div class="rs-container"><div><span>✉</span><p><strong>Stay Informed. Stay Inspired.</strong><small>Subscribe to our newsletter and never miss an update on events, programs and inspiring stories.</small></p><form><input type="email" aria-label="Email address" placeholder="Enter your email"><button type="submit">Subscribe &nbsp;→</button></form></div></div></section>
</main>
<?php get_footer(); ?>
